name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set version
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "version=.*"
          replace: "version=${{ github.ref }}"
          regex: true
          include: './gradle.properties'
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Assemble with Gradle
        run: ./gradlew clean test assemble
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: 'build/libs/auto-changelog*.jar'
